nelmio_cors:
        defaults:
            allow_credentials: true
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 3600
            hosts: []
            origin_regex: true
            forced_allow_origin_value: '*'
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_headers: ['Content-Type','Authorization']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH']
                max_age: 3600