<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlSpuqC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlSpuqC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXlSpuqC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXlSpuqC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXlSpuqC\App_KernelDevDebugContainer([
    'container.build_hash' => 'XlSpuqC',
    'container.build_id' => '4d1b3d4d',
    'container.build_time' => 1616446745,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlSpuqC');
