<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCMRO25\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCMRO25/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXCMRO25.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXCMRO25\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXCMRO25\App_KernelDevDebugContainer([
    'container.build_hash' => 'XCMRO25',
    'container.build_id' => 'c03981f1',
    'container.build_time' => 1616436407,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCMRO25');
